### ISSUE TITLE
In @font-face blocks, dashes in property names become 'undefined'.

### ISSUE THREAD

**Issue by pygy** [j2css/j2c-importer#3]
``` CSS
@font-face {
  font-family: "Bitstream Vera Serif Bold";
}
```

Becomes 

``` JS
{
  '@global': {
    '@font-face': {
      fontundefinedamily: '"Bitstream Vera Serif Bold"'
    }
  }
}
```
